import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import myciedssidebar from "./docs/mycieds/sidebar";
import crudsidebar from "./docs/crud/sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'For Developers',
      items:[
        'changelog',
        'documents/commonDoc',
      ],
    },
    {
      type: 'category',
      label: 'For Database Administrators',
      items:[
        'documents/doc3',
        'documents/doc4',
      ],
    },
  ],
  mycieds: [
    {
      type: "category",
      label: "MyCIEDS",
      link: {
        type: "generated-index",
        title: "MyCIEDS API",
        description:
        "This is a sample server MyCIEDS server. You can find out more about at ",
        slug: "/category/mycieds-api",
      },
      items: myciedssidebar,
    }
  ],
  crud: [
    {
      type: "category",
      label: "CRUD",
      link: {
        type: "generated-index",
        title: "CRUD API",
        description:
        "This is a sample server CRUD server. You can find out more about at ",
        slug: "/category/crud-api",
      },
      items: crudsidebar,
    }
  ],
  
};

export default sidebars;
