import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "myciedscors/sdsie-api",
    },
    {
      type: "category",
      label: "AbpApiDefinition",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AbpApplicationConfiguration",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AbpApplicationLocalization",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AbpTenant",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Account",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AccountExternalProvider",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AccountSettings",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Announcement",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "AnnouncementAttachment",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Applications",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "AuditLogs",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Bucket",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "ChangeRequest",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ChangeRequestAttachment",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "City",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ClaimType",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Company",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CompanyApp",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CompanyAppAttachment",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "CompanyAppDirector",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CompanyAppInquiry",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "CompanyDirector",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "DynamicClaims",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Edition",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "EmailSettings",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ExternalLogin",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "File",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Form",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormActivityLog",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "FormCooFta",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormDocument",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "FormDocumentType",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormExemption",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormInquiry",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormInspection",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormPair",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormRmk",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "FormStatus",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FormVersion",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "HangfireJob",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Inbox",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "InboxAttachment",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Languages",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "LanguageTexts",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "MyAccount",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MyAuditLogs",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MyIdentityRole",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "MyIdentityUser",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MyProfile",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "OrganizationUnit",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Permissions",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Postcode",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Role",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Scopes",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "SecurityLog",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sessions",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "SmkTransaction",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SmkTransactionLog",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "State",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Station",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "StationState",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tenant",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "TextTemplateContents",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "TextTemplateDefinitions",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "TimeZoneSettings",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "User",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "UserHistory",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "UserLookup",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "UserManual",
      items: [
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "myciedscors/",
          label: "Missing summary",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
